'use client'

import { useState } from 'react'
import { useLiveSession } from '../../lib/useLiveSession'
import { LiveTranscript } from './LiveTranscript'
import { LiveClaimCard } from './LiveClaimCard'

const PROVISIONAL_DISCLAIMER =
  'Live fact-checking is AI-assisted and provisional. Verdicts are generated in real time, are not yet human-reviewed, and may be wrong. Treat them as a prompt to check further, not a final judgement. Generated by AI.'

export function LiveConsole() {
  const session = useLiveSession()
  const [url, setUrl] = useState('')

  const isLive = session.status === 'active'
  const resolvedClaims = session.claims.filter((c) =>
    ['supported', 'disputed', 'needs_context', 'unverifiable'].includes(c.status),
  ).length

  return (
    <div className="space-y-5">
      {/* Always-visible provisional banner (legal requirement) */}
      <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-3">
        <p className="text-xs leading-relaxed text-amber-200/90">
          <span className="font-semibold uppercase tracking-wider">Live · AI-assisted · provisional.</span>{' '}
          {PROVISIONAL_DISCLAIMER}
        </p>
        {session.electionMode && (
          <p className="mt-2 text-xs font-medium text-amber-100">
            Election-period mode is on: claims about a named candidate&rsquo;s character are not shown.
          </p>
        )}
      </div>

      {/* Setup */}
      {session.status !== 'active' && (
        <form
          onSubmit={(e) => {
            e.preventDefault()
            void session.start(url)
          }}
          className="space-y-3"
        >
          <div className="flex flex-col gap-2 rounded-2xl border border-white/10 bg-forest-950 p-2 sm:flex-row sm:items-center">
            <input
              type="url"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              placeholder="Paste a live stream URL — YouTube Live, X, news HLS…"
              className="w-full flex-1 bg-transparent px-4 py-3 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none"
            />
            <button
              type="submit"
              disabled={!url.trim() || session.status === 'starting'}
              className="shrink-0 rounded-full bg-parchment px-5 py-2.5 text-sm font-medium text-forest-950 transition-colors hover:bg-white disabled:opacity-50"
            >
              {session.status === 'starting' ? 'Connecting…' : 'Go live'}
            </button>
          </div>

          {session.needsLogin && (
            <p className="text-xs text-amber-300">
              <a href="/login?next=/live" className="underline">Sign in</a> to start a live session.
            </p>
          )}
          {session.status === 'error' && session.error && (
            <p className="text-xs text-red-300">{session.error}</p>
          )}
          {session.status === 'ended' && (
            <p className="text-xs text-zinc-500">Session ended. Paste another URL to start again.</p>
          )}
        </form>
      )}

      {/* Console */}
      {isLive && (
        <>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 animate-pulse rounded-full bg-red-500" />
              <span className="font-mono text-xs uppercase tracking-widest text-zinc-400">
                Live · {resolvedClaims}/{session.claims.length} checked
              </span>
            </div>
            <button
              onClick={() => void session.stop()}
              className="rounded-full border border-white/15 px-4 py-1.5 text-xs font-medium text-zinc-300 hover:bg-white/5"
            >
              End session
            </button>
          </div>

          <div className="grid gap-4 lg:grid-cols-2">
            <div className="h-[28rem] rounded-2xl border border-white/10 bg-forest-950 p-5">
              <LiveTranscript chunks={session.transcript} />
            </div>
            <div className="flex h-[28rem] flex-col rounded-2xl border border-white/10 bg-forest-950 p-5">
              <p className="mb-3 font-mono text-[11px] uppercase tracking-widest text-zinc-500">Claims</p>
              <div className="flex-1 space-y-3 overflow-y-auto pr-1">
                {session.claims.length === 0 && (
                  <p className="text-sm text-zinc-600">Watching for check-worthy claims…</p>
                )}
                {[...session.claims].reverse().map((c) => (
                  <LiveClaimCard key={c.id} claim={c} />
                ))}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  )
}
