import type { Metadata } from 'next'
import Link from 'next/link'
import { Container, Eyebrow } from '@fountem/ui'

export const metadata: Metadata = {
  title: 'Disclaimer & Right of Reply — Fountem',
  description: 'The limits of Fountem verdicts, and how to challenge one.',
}

export default function DisclaimerPage() {
  return (
    <Container size="narrow">
      <article className="py-14">
        <Eyebrow>Legal</Eyebrow>
        <h1 className="mt-3 font-serif text-4xl text-forest-900">Disclaimer &amp; right of reply</h1>
        <p className="mt-2 text-sm text-ink-muted">Last updated: June 2026.</p>

        <div className="mt-10 space-y-10 leading-relaxed text-ink-secondary">
          <Section title="Verdicts are evidence-backed assessments">
            Every Fountem verdict is an <strong className="text-ink">assessment based on the cited evidence, not
            definitive proof</strong>. Evidence can be incomplete, contested, or superseded. Where the evidence is
            inadequate we say <em>unverifiable</em> rather than guess. We show the sources behind every verdict so you
            can check our work.
          </Section>
          <Section title="AI-generated text">
            Verdict text is generated by AI language models grounded in the cited evidence, and may be human-reviewed
            before publication. We disclose this so you can weigh it appropriately.
          </Section>
          <Section title="No reliance; not advice">
            Do not rely on a verdict as the sole basis for any decision, publication or allegation. A verdict is one
            input alongside the primary sources and your own judgement. Fountem is non-partisan, is not affiliated with
            any party or campaign, does not tell anyone how to vote, and does not provide legal or professional advice.
            See our <Link href="/terms" className="font-medium text-forest-700 underline">terms</Link>.
          </Section>
          <Section title="Right of reply, corrections and removal">
            If you are the subject of a verdict and believe it is wrong or unfair, you can challenge it and provide
            evidence. We aim to acknowledge within 2 working days and resolve within 10, and we correct rather than
            silently delete &mdash; amended verdicts are marked as updated. Contact{' '}
            <span className="text-ink">corrections@fountem.ai</span> (or{' '}
            <span className="text-ink">legal@fountem.ai</span> for legal matters, and{' '}
            <span className="text-ink">privacy@fountem.ai</span> to exercise data-protection rights).
          </Section>
        </div>
      </article>
    </Container>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-2 font-serif text-2xl text-forest-900">{title}</h2>
      <div>{children}</div>
    </section>
  )
}
